### PR TITLE
Big refactor to simplify API

### PR DESCRIPTION
**Pull request by gracecodes144**
Signed-off-by: Aaron Browne aaron0browne@gmail.com

### CODE REVIEW

**Comment by gracecodes144** [comment]
Thoughts @bruth?

**Comment by bruth** [comment]
Since this is being diffed against the previous code which was only partially reviewed, I am not inclined to review this very much since it will likely be refined a few more times. Writing tests and making sure it works is the first priority. That being said is there anything specifically you want me to look at?

**Comment by gracecodes144** [comment]
I made changes mostly in response to [this](https://github.com/chop-dbhi/data-models-packer/commit/515e86deec5b81dde363ddb3d8083ebf11fa2412#commitcomment-15274176), [this](https://github.com/chop-dbhi/data-models-packer/commit/515e86deec5b81dde363ddb3d8083ebf11fa2412#commitcomment-15274631), and [this](https://github.com/chop-dbhi/data-models-packer/commit/515e86deec5b81dde363ddb3d8083ebf11fa2412#commitcomment-15274816) comment. In particular, there is now a PackageWriter and a PackageReader that encapsulates all the business logic.

I can just merge and then you can review the whole thing for quality, if that's better.

**Comment by bruth** [comment]
Yes that would be better.

**Comment by bruth** [comment]
A few observations:
- I am not sure what [this](https://github.com/chop-dbhi/data-models-packer/blob/master/cmd/packer/main.go#L16-L24) means. In general, I've never seen a case where a panic occurs when it is not a programmer error (or a bug in the library). Also I notice you are checking `os.Args`, but that is prior to the flag parsing.
- This is a nit, but variable declarations should be as close to the assignment of them as possible. For example [this](https://github.com/chop-dbhi/data-models-packer/blob/master/cmd/packer/main.go#L94) variable is not assigned until after a few unrelated things happen some of which could exit the program. Obviously make your best judgement for this, but I just wanted to point it out. It is analogous to the debate of declaring all JavaScript variables at the top of the function versus declaring them as you go.
- [This snippet](https://github.com/chop-dbhi/data-models-packer/blob/master/cmd/packer/main.go#L149-L154) tells me the that function is dependent on the `VerifyOnly` flag on to be true to actually do something (I haven't looked at the method implementation yet). If this is true, then this flag has to do with control flow which should be done outside of the function call, e.g.

``` go
if verifyOnly {
    if err = packer.CreateOrVerifyMetadataFiled(cfg); err != nil {
    }
}
```

Moving this to a flag (rather than a config option) would decouple the control flow and prevent needing to set the option to true in the above linked code.
- Variables that are reused should not be declared inside functions, but at the top of the file, such as [here](https://github.com/chop-dbhi/data-models-packer/blob/master/config.go#L100-L106).
- If the keys are predefined and no iteration is required, it is more idiomatic to define a struct instead of using a map as temporary data structures, such as [here](https://github.com/chop-dbhi/data-models-packer/blob/master/config.go#L57-L64). There is also less overhead to structs than maps.

**Comment by gracecodes144** [comment]
Responses:

If the user invokes the binary with no arguments, the program flow assumes it is unpacking an unencrypted tar and gzip'd package from STDIN to the cwd. This is hypothetically a valid usage. However, if there is nothing on STDIN, the `tar` package panics. I suppose this could be called a bug in the library. The problem I'm trying to avoid with [this](https://github.com/chop-dbhi/data-models-packer/blob/master/cmd/packer/main.go#L16-L24) code is displaying a panic when a user simply invokes the binary without piping anything, which seems like it might be a valid if misguided way to first interact with the binary. After commenting out the panic-catching code, this is what happens in the situation described: 

```
$ data-models-packer
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x1028b5]

goroutine 1 [running]:
archive/tar.(*Reader).Next(0x0, 0xc8200c60b0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/archive/tar/reader.go:92 +0x45
github.com/chop-dbhi/data-models-packer.(*DecompressingReader).Next(0xc8200aa540, 0x692100, 0x0, 0x0)
    /Users/brownea/Projects/go/src/github.com/chop-dbhi/data-models-packer/unpack.go:286 +0x2ca
github.com/chop-dbhi/data-models-packer.(*PackageReader).Next(0xc8200aa500, 0x1, 0x0, 0x0)
    /Users/brownea/Projects/go/src/github.com/chop-dbhi/data-models-packer/unpack.go:80 +0x30
github.com/chop-dbhi/data-models-packer.(*PackageReader).Unpack(0xc8200aa500, 0x0, 0x0)
    /Users/brownea/Projects/go/src/github.com/chop-dbhi/data-models-packer/unpack.go:151 +0xbc
main.main()
    /Users/brownea/Projects/go/src/github.com/chop-dbhi/data-models-packer/cmd/packer/main.go:69 +0x6dc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1
```

With the panic-catching code, that use case will instead print the help. I suppose the code could be more specific to the situation I've described, and print an error message instead, if I moved it deeper into the package somewhere, like [here](https://github.com/chop-dbhi/data-models-packer/blob/master/unpack.go#L286).

Variable declaration closer to assignment nit registered. I will look out for it moving forward.

The `CreateOrVerifyMetadataFile` function definitely does do something if the `verifyOnly` boolean is false. It is needed both inside the function, [here](https://github.com/chop-dbhi/data-models-packer/blob/master/metadata.go#L77), and in the program flow, [here](https://github.com/chop-dbhi/data-models-packer/blob/master/cmd/packer/main.go#L109), but I think you're right that it should be independent of the config object.

I'll move the error declarations out of the function call.

I'll convert the map to a struct.

**Comment by bruth** [comment]
Thank you for the response. I am surprised by the `tar` package behavior, but obviously it needs to be handled.

**Comment by gracecodes144** [comment]
Made some changes and submitted PR #6.

**Pull request merged**
